dist: bionic
language: python
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
services:
  - docker

install: skip # so travis doesn't do pip install requirements.txt
script:
  - docker build -f py.Dockerfile --build-arg MUJOCO_KEY=$MUJOCO_KEY --build-arg PYTHON_VER=$PY_VER -t gym-test .
  - docker run gym-test 

deploy:
    provider: pypi
    username: $TWINE_USERNAME
    password: $TWINE_PASSWORD
    on:
        tags: true
        python: 3.7
